# Generated by Django 3.1.1 on 2020-10-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='context',
            new_name='content',
        ),
    ]
