# Generated by Django 3.1.2 on 2020-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201007_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
